### ISSUE TITLE
Modis_collect should fail when .hdf cannot be read

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#139] opened 2020-12-09 20:51 UTC
When a downloaded .hdf is corrupt, this is detected and reported by modis_collect. Then, the script continues by inserting NoData; consider breaking here.

**Comment by valpesendorfer** [comment] 2020-12-09 20:56
Should it fail? The very least it should not included in `.collected`

**Comment by interob** [comment] 2020-12-09 20:59
Correct regarding the `.collected`.

Sorry, I thought your position (or our conclusion) was that it should fail. If not: fine by me. I hope to never end up in that scenario anyway, since I will choose for downloading with hash verfication.

**Comment by valpesendorfer** [comment] 2020-12-09 21:00
I'll give it another thought. But I think for a normal user, it would be nice if it wouldn't fail, as a missing datapoint won't make a big difference. 

Could imagine adding a flag a la `--skip-corrupt` or similar

**Comment by interob** [comment] 2020-12-09 21:03
Yes. Or the other way around: `--fail-on-corrupt-timestep`

**Comment by valpesendorfer** [comment] 2020-12-09 21:07
Maybe more concise? `--fail-if-the-data-is-corrupt-even-the-download-went-apparenly-ok-but-still-theres-some-issue-so-please-fail` ? :smile:

**Comment by interob** [comment] 2020-12-09 21:11
I would not dare clutter your issue tracker... But yes, something with that level of nuance is what I am looking for!

**Comment by valpesendorfer** [comment] 2020-12-31 17:59
As documented in #137 , even "corrupted" HDF files will be included in the `.collected` tracefile. Initially I thought this to be an unintended behaviour, but I went back through the issues and this is _actually_ how we decided to do it. Maybe there was some confusion with the naming, and the fact that we hadn't considered this case.

In #97 you write:
>It would be best if modis_collect leaves a trace of the delete file, e.g. an (empty) .ingested file with otherwise the same name

So the question now is, should we only included actually "collected" files in `.collected` and "silently" delete the corrupt ones?

**Comment by interob** [comment] 2021-01-02 13:40
I think best would be to raise an exception: nobody wants a corrupt .hdf sitting in his disk... Question is: how does one find out it is corrupt? Preferably NOT by staring a MODAPE output to console, but rather by a process breaking

**Comment by valpesendorfer** [comment] 2021-01-02 16:38
I think there's a case for using no-data in lieu of a corrupt HDF file, and therefore not breaking the process. 

We could implement the default way as raising an exception, and then having an override flag. But, that leaves the essential question: if corrupt and the process goes on, does it go into the .collected?

**Comment by valpesendorfer** [comment] 2021-01-02 16:38
Whoops, not meant to close

**Comment by interob** [comment] 2021-01-02 18:56
How about NOT into .collected and also NOT remove the .hdf from disk (clean up)

**Comment by interob** [comment] 2021-01-02 22:35
> I think there's a case for using no-data in lieu of a corrupt HDF file, and therefore not breaking the process.
> 
> We could implement the default way as raising an exception, and then having an override flag. But, that leaves the essential question: if corrupt and the process goes on, does it go into the .collected?

+1 for adding an override flag (default: raise exception)

**Comment by valpesendorfer** [comment] 2021-01-03 19:26
Ok, great. Will have a PR tomorrow.

**Comment by valpesendorfer** [comment] 2021-01-04 12:21
fixed with #151

**Closed by valpesendorfer** 2021-01-04 12:21 UTC
Labels: suggestion
