### ISSUE TITLE
Error updating raw H5

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#54] opened 2019-06-18 07:19 UTC
In the process of ingesting NDVI one year after another, I got this error during processing of the second year:

Error updating ./VIM/MXD13A2.h19v08.006.VIM.h5! File may be corrupt, consider creating the file from scratch, or closer investigation.

Error message:

Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\modape\modis.py", line 472, in update
    arr[..., b1:b1+self.chunks[1]] = dset[b:b+self.chunks[0], b1:b1+self.chunks[1]]
ValueError: could not broadcast input array from shape (48,10) into shape (57600,10)

Error processing product ['MXD13A2'], product code None.

 Traceback:

Traceback (most recent call last):
  File "D:\ARC\Documents\2019\VAM NDVI\africa_1km\scripts\modis_collect.py", line 36, in run_process
    rh5.update()
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\modape\modis.py", line 472, in update
    arr[..., b1:b1+self.chunks[1]] = dset[b:b+self.chunks[0], b1:b1+self.chunks[1]]
ValueError: could not broadcast input array from shape (48,10) into shape (57600,10)

**Comment by valpesendorfer** [comment] 2019-06-18 08:37
The error seems to come from ingesting corrupt data. In this case, you need to identify and replace the corrupt raw files, remove the raw hdf5 file `./VIM/MXD13A2.h19v08.006.VIM.h5` and create a new one with `modis_collect`.

While there could be improvements with handling and logging this situations, it's an expected behaviour and not a bug. Therefore I will close the issue.

Thanks for reporting @interob !

**Comment by valpesendorfer** [comment] 2019-06-18 16:19
Re-opened - is actually a bug when updating the dataset, was just masked by corrupt data

**Closed** 2019-06-18 16:44 UTC
Labels: bug
