### ISSUE TITLE
Use modis_window as API: allow to pass-in rich set GDAL parameters (incl. dataset metadata) and return list of exported mosaics/subsets

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#128] opened 2020-11-25 12:25 UTC
Enhancements:
1. def cli() needs to return the filenames of the exported mosaics/subsets (this builds on PR https://github.com/WFP-VAM/modape/pull/120)
2. support passing roi as a list[float] (currently modis_window assumes a string and always parses it into list[float])
3. support passing gdal_kwarg as a dict (currently modis_window assumes a Tuple[str] (["key=value", .. ] ) and always parses it into a dict)

Will submit a PR implementing the above

**Comment by valpesendorfer** [comment] 2020-11-28 15:55
This is a bit of an issue. Using it as a commandline script (as intended) prohibits the easy use of list & dict for `roi` and `gdal_kwarg`, respectively.

**Comment by interob** [comment] 2020-11-29 22:32
Through Click, one can pass to modis_window only a tuple of "key=value" pair; however, what is needed to add metadata to the exported TIFF is passing a nested list, like this:
`{ 'xRes': 0.01, 'yRes': 0.01, 'metadataOptions': ['FINAL=FALSE', 'CONSOLIDATION_STAGE={}'] }`

**Comment by valpesendorfer** [comment] 2020-12-19 19:14
addressed by #130

**Closed by valpesendorfer** 2020-12-19 19:14 UTC
Labels: feature-request
